global:
  scrape_interval: 5s

scrape_configs:
  # Locust metrics
  - job_name: "locust"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9646"

  # Node Exporter metrics
  - job_name: "node"
    static_configs:
      - targets:
          - "host.docker.internal:9100"

  # CloudWatch Exporter metrics
  - job_name: "cloudwatch"
    static_configs:
      - targets:
          - "host.docker.internal:9106"

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']