global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Locust metrics
  - job_name: "locust"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9646"

  # Node Exporter metrics
  - job_name: "node"
    static_configs:
      - targets:
          - "host.docker.internal:9100"

  # CloudWatch Exporter metrics
  - job_name: "cloudwatch"
    static_configs:
      - targets:
          - "cloudwatch-exporter:9106"

  # CI/CD metrics pushed from GitHub Actions
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
