global:
  scrape_interval: 5s

scrape_configs:
  # Locust metrics
  - job_name: "locust"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:9646"

  # Node Exporter metrics
  - job_name: "node"
    static_configs:
      - targets:
          - "host.docker.internal:9100"

  # CloudWatch Exporter metrics
  - job_name: "cloudwatch"
    static_configs:
      - targets:
          - "host.docker.internal:9106"

  # Local Pushgateway (for testing on your machine)
  - job_name: "pushgateway_local"
    static_configs:
      - targets: ["pushgateway:9091"]

  # Ngrok Pushgateway (for GitHub Actions jobs)
  - job_name: "pushgateway_ci"
    honor_labels: true
    static_configs:
      - targets: ["homelike-lobularly-nilsa.ngrok-free.dev"]   # replace with your ngrok URL
