name: CI - QA Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: |
          mkdir -p reports/pytest
          pytest pytest/ --maxfail=1 --disable-warnings -q --junitxml=reports/pytest/results.xml

      - name: Run Robot Framework tests
        run: |
          mkdir -p reports/robot
          robot --output reports/robot/output.xml --report reports/robot/report.html --log reports/robot/log.html robot/api_tests.robot

      - name: Run Locust load tests
        run: |
          mkdir -p reports/locust
          locust -f Locust/locustfile.py \
              --headless \
              -u 10 -r 2 -t 1m \
              --host https://prl0fjqceh.execute-api.us-east-1.amazonaws.com \
              --csv reports/locust/results || true


      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda function
        run: |
          zip -r lambda_function.zip lambda_function.py
          aws lambda update-function-code \
            --function-name helloLambda \
            --zip-file fileb://lambda_function.zip

      - name: Redeploy API Gateway stage
        run: |
          aws apigateway create-deployment \
            --rest-api-id prl0fjqceh \
            --stage-name dev
